angular.module('mainMod').config(function($urlRouterProvider,$stateProvider){
    //$urlRouterProvider.otherwise('/');
    $stateProvider.state('home',{
        url:'/home',
        templateUrl:'partials/home.html'
    })
    $stateProvider.state('about',{
        url:'/about',
        templateUrl:'partials/about.html'
    })
})